package com.example.privyping.ui.media_analysis

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import android.util.Base64
import com.example.privyping.BuildConfig
import okhttp3.*
import okhttp3.MediaType.Companion.toMediaType
import org.json.JSONArray
import org.json.JSONObject
import java.io.ByteArrayOutputStream
import java.util.concurrent.TimeUnit
import android.util.Log
import java.io.IOException


object HFImageAnalyzer {

    // AI-generated image detector
    private const val ENDPOINT =
        "https://router.huggingface.co/hf-inference/models/umm-maybe/AI-image-detector"

    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .build()

    fun analyze(
        context: Context,
        imageUri: Uri,
        onResult: (ImageAnalysisResult) -> Unit,
        onError: (String) -> Unit
    ) {
        Log.d("HFImageAnalyzer", "Analyze called")

        try {
            // Decode & compress image
            val bitmap = BitmapFactory.decodeStream(
                context.contentResolver.openInputStream(imageUri)
            )

            val outputStream = ByteArrayOutputStream()
            bitmap.compress(Bitmap.CompressFormat.JPEG, 85, outputStream)
            val imageBytes = outputStream.toByteArray()

            val base64 = Base64.encodeToString(imageBytes, Base64.NO_WRAP)

            val requestBody = JSONObject()
                .put("inputs", base64)
                .toString()

            val request = Request.Builder()
                .url(ENDPOINT)
                .post(
                    RequestBody.create(
                        "application/json".toMediaType(),
                        requestBody
                    )
                )
                .addHeader("Authorization", "Bearer ${BuildConfig.HF_API_KEY}")
                .build()

            client.newCall(request).enqueue(object : Callback {
                override fun onFailure(call: Call, e: IOException) {
                    Log.e("HFImageAnalyzer", "Network failure", e)
                    onError("Network error: ${e.message}")
                }


                override fun onResponse(call: Call, response: Response) {
                    val body = response.body?.string()

                    Log.d("HFImageAnalyzer", "HTTP Code: ${response.code}")
                    Log.d("HFImageAnalyzer", "Response Body: ${body ?: "null"}")

                    if (!response.isSuccessful || body == null) {
                        onError("API Error (${response.code})")
                        return
                    }

                    try {
                        parseResponse(body, onResult)
                    } catch (e: Exception) {
                        onError("Parsing error: ${e.message}")
                    }
                }


            })

        } catch (e: Exception) {
            onError("Error: ${e.message}")
        }
    }

    private fun parseResponse(
        body: String,
        onResult: (ImageAnalysisResult) -> Unit
    ) {
        /*
          Example HF response:
          [
            { "label": "AI", "score": 0.92 },
            { "label": "REAL", "score": 0.08 }
          ]
        */

        val arr = JSONArray(body)
        var aiScore = 0.0
        var realScore = 0.0

        for (i in 0 until arr.length()) {
            val obj = arr.getJSONObject(i)
            when (obj.getString("label").uppercase()) {
                "AI" -> aiScore = obj.getDouble("score")
                "REAL" -> realScore = obj.getDouble("score")
            }
        }

        val aiPercent = (aiScore * 100).toInt()
        val realPercent = (realScore * 100).toInt()

        val verdict: String
        val confidence: Int
        val summary: String

        when {
            aiPercent >= 70 -> {
                verdict = "AI"
                confidence = aiPercent
                summary = "High likelihood this image was generated by AI."
            }

            realPercent >= 70 -> {
                verdict = "REAL"
                confidence = realPercent
                summary = "Image likely originates from a real camera source."
            }

            else -> {
                verdict = if (aiPercent > realPercent) "AI" else "REAL"
                confidence = maxOf(aiPercent, realPercent)
                summary = "The image shows mixed signals but leans towards being ${if (aiPercent > realPercent) "AI generated" else "real"}."
            }
        }

        onResult(
            ImageAnalysisResult(
                isAiGenerated = verdict == "AI",
                confidence = confidence,
                summary = summary,
                keyPatterns = listOf(
                    "Texture consistency",
                    "Noise distribution",
                    "Edge coherence",
                    "Lighting realism"
                )
            )
        )
    }
}
